In [1]:
# coding: utf-8
import numpy as np


class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))


class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 重みとバイアスの初期化
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # レイヤの生成
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # すべての重みをリストにまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[1.44847393 2.25510283 1.76953186]
 [0.59244716 1.80852657 0.89964086]
 [0.54590013 1.48189232 0.6508547 ]
 [1.53524354 2.97133862 2.15649195]
 [0.73998564 1.65226838 1.00068993]
 [0.64289693 1.4657194  0.8197837 ]
 [0.713905   1.27725553 0.83082146]
 [1.01064282 2.47240876 1.5612752 ]
 [1.228383   2.79065887 1.85246044]
 [1.01585548 1.35441542 1.11529484]]
